export const projectsData = [
  {
    id: 1,
    title: "Modern Office Complex",
    category: "Commercial",
    location: "Downtown Business District",
    budget: "$2.5M",
    duration: "14 months",
    team: "25 workers",
    image:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
    description:
      "A state-of-the-art 5-story office building featuring sustainable design, smart building technology, and modern amenities.",
    longDescription:
      "This ambitious project involved the construction of a cutting-edge 5-story office complex designed to meet the demands of modern businesses. We integrated sustainable building practices, including energy-efficient HVAC systems and rainwater harvesting, to minimize environmental impact. The interior boasts flexible workspaces, advanced networking infrastructure, and collaborative zones, all designed to foster productivity and innovation. The project was completed on schedule and within budget, becoming a landmark in the downtown business district.",
    features: [
      "5-story modern design",
      "Sustainable building practices",
      "Smart building technology",
      "Flexible workspaces",
      "Advanced networking infrastructure",
    ],
    challenges: [
      "Navigating strict urban planning regulations",
      "Integrating complex smart building systems",
      "Minimizing disruption in a busy downtown area",
    ],
    solutions: [
      "Proactive engagement with city planners",
      "Utilizing BIM for seamless system integration",
      "Implementing phased construction and off-hours work",
    ],
    status: "Completed",
    year: "2024",
    galleryImages: [
      "/images/project-gallery-1.jpeg",
      "/images/project-gallery-2.jpeg",
      "/images/project-gallery-3.jpeg",
      "/images/project-collage-1.png",
      "/images/project-collage-2.png",
    ],
  },
  {
    id: 2,
    title: "Luxury Residential Villa",
    category: "Residential",
    location: "Hillside Estates",
    budget: "$1.8M",
    duration: "10 months",
    team: "18 workers",
    image:
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
    description: "Custom-built luxury home with premium finishes, smart home integration, and panoramic city views.",
    longDescription:
      "Nestled in the exclusive Hillside Estates, this custom-built luxury villa is a testament to bespoke craftsmanship and modern living. Every detail, from the imported marble flooring to the custom cabinetry, was meticulously selected and installed. The home features a fully integrated smart home system controlling lighting, climate, security, and entertainment. Large panoramic windows offer breathtaking city views, creating a seamless connection between indoor comfort and outdoor beauty. This project exemplifies our dedication to creating dream homes.",
    features: [
      "Custom architectural design",
      "Premium interior and exterior finishes",
      "Integrated smart home technology",
      "Panoramic city views",
      "Landscaped gardens and outdoor living spaces",
    ],
    challenges: [
      "Complex hillside foundation work",
      "Sourcing rare and high-end materials",
      "Coordinating multiple specialized subcontractors",
    ],
    solutions: [
      "Advanced geotechnical surveys and reinforced foundation design",
      "Global network of suppliers for material procurement",
      "Rigorous project management and communication protocols",
    ],
    status: "Completed",
    year: "2024",
    galleryImages: [
      "/images/project-gallery-4.jpeg",
      "/images/project-gallery-5.jpeg",
      "/images/project-gallery-6.jpeg",
      "/images/project-collage-3.png",
      "/images/project-collage-4.png",
    ],
  },
  {
    id: 3,
    title: "Shopping Center Renovation",
    category: "Renovation",
    location: "Westside Mall",
    budget: "$3.2M",
    duration: "8 months",
    team: "30 workers",
    image: "/images/project-temple.jpeg",
    description:
      "Complete transformation of a dated shopping center into a modern retail destination with updated facades and interiors.",
    longDescription:
      "This extensive renovation project breathed new life into the aging Westside Mall, transforming it into a vibrant, modern retail hub. The scope included a complete overhaul of the exterior facade, new roofing, and a significant redesign of the interior common areas. We upgraded all public restrooms, installed new energy-efficient lighting, and improved accessibility throughout the mall. The project was executed in phases to minimize disruption to existing tenants and shoppers, ensuring business continuity during construction.",
    features: [
      "Full exterior facade upgrade",
      "Modernized interior common areas",
      "New energy-efficient lighting systems",
      "Improved accessibility features",
      "Phased construction for minimal disruption",
    ],
    challenges: [
      "Working within an active commercial environment",
      "Adhering to strict timelines to avoid peak season impact",
      "Managing complex logistics for material delivery and waste removal",
    ],
    solutions: [
      "Detailed scheduling and off-hours work for noisy tasks",
      "Close coordination with mall management and tenants",
      "Dedicated on-site logistics team for efficient operations",
    ],
    status: "Completed",
    year: "2023",
    galleryImages: [
      "/images/project-gallery-7.jpeg",
      "/images/project-gallery-8.jpeg",
      "/images/project-gallery-9.jpeg",
      "/images/project-collage-5.png",
      "/images/project-collage-6.jpeg",
    ],
  },
  {
    id: 4,
    title: "Industrial Warehouse",
    category: "Industrial",
    location: "Industrial Park East",
    budget: "$1.2M",
    duration: "6 months",
    team: "20 workers",
    image:
      "https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
    description: "Large-scale warehouse facility with advanced logistics systems and energy-efficient design.",
    longDescription:
      "We constructed a large-scale industrial warehouse designed for optimal logistics and storage efficiency. The facility features high ceilings, multiple loading docks, and a reinforced concrete floor capable of supporting heavy machinery and racking systems. Energy efficiency was a key consideration, with the installation of LED lighting, insulated panels, and a smart climate control system. This project provides a robust and adaptable space for various industrial operations.",
    features: [
      "High-capacity storage space",
      "Multiple loading docks",
      "Reinforced concrete flooring",
      "Energy-efficient lighting and insulation",
      "Advanced security systems",
    ],
    challenges: [
      "Expedited construction timeline",
      "Large-scale concrete pouring and curing",
      "Integrating specialized material handling equipment",
    ],
    solutions: [
      "Double shifts and efficient resource allocation",
      "Utilizing high-strength, fast-curing concrete mixes",
      "Close collaboration with equipment suppliers during design phase",
    ],
    status: "Completed",
    year: "2023",
    galleryImages: [
      "/images/construction-site-1.jpeg",
      "/images/construction-site-2.jpeg",
      "/images/construction-site-3.jpeg",
      "/images/construction-site-4.jpeg",
    ],
  },
  {
    id: 5,
    title: "Healthcare Facility",
    category: "Healthcare",
    location: "Medical District",
    budget: "$4.5M",
    duration: "18 months",
    team: "35 workers",
    image: "https://images.unsplash.com/photo-1551601651-2a8555f1a136?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
    description: "Modern medical center with specialized equipment installations and patient-centered design.",
    longDescription:
      "This project involved the construction of a modern healthcare facility, designed with patient comfort and operational efficiency in mind. The building incorporates specialized areas for diagnostics, treatment, and recovery, all equipped with state-of-the-art medical technology. We focused on creating a calming environment with ample natural light and intuitive layouts. Strict adherence to healthcare building codes and sanitation standards was paramount throughout the construction process.",
    features: [
      "Specialized diagnostic and treatment areas",
      "State-of-the-art medical equipment integration",
      "Patient-centered design with natural light",
      "Advanced air filtration systems",
      "Compliance with all healthcare regulations",
    ],
    challenges: [
      "Meeting stringent healthcare safety and hygiene standards",
      "Coordinating complex medical equipment installations",
      "Ensuring minimal disruption to surrounding medical facilities",
    ],
    solutions: [
      "Dedicated quality control and safety teams",
      "Phased installation and rigorous testing of equipment",
      "Strategic scheduling and noise reduction measures",
    ],
    status: "In Progress",
    year: "2024",
    galleryImages: [
      "/images/concrete-pouring-1.jpeg",
      "/images/concrete-pouring-2.jpeg",
      "/images/concrete-pouring-3.jpeg",
      "/images/concrete-pouring-4.jpeg",
    ],
  },
  {
    id: 6,
    title: "Educational Campus",
    category: "Educational",
    location: "University District",
    budget: "$6.8M",
    duration: "24 months",
    team: "45 workers",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300",
    description: "New academic building with state-of-the-art classrooms, laboratories, and collaborative spaces.",
    longDescription:
      "We constructed a new academic building as part of a university campus expansion, providing state-of-the-art learning and research environments. The facility includes flexible classrooms, advanced science laboratories, a large lecture hall, and various collaborative study areas. We prioritized sustainable design, incorporating green roofs and efficient insulation. The project was designed to foster an engaging and inspiring educational experience for students and faculty.",
    features: [
      "Flexible classrooms and lecture halls",
      "Advanced science and research laboratories",
      "Collaborative study and common areas",
      "Sustainable design elements (green roof, efficient insulation)",
      "Integrated audiovisual and IT infrastructure",
    ],
    challenges: [
      "Coordinating with university academic calendar",
      "Ensuring accessibility for all students",
      "Managing complex MEP systems for laboratories",
    ],
    solutions: [
      "Off-peak construction scheduling during breaks",
      "Universal design principles implemented from planning phase",
      "Specialized engineering teams for lab infrastructure",
    ],
    status: "In Progress",
    year: "2024",
    galleryImages: [
      "/images/surveying-site.jpeg",
      "/images/construction-site-5.jpeg",
      "/images/concrete-pouring-5.jpeg",
      "/images/project-survey.jpeg",
    ],
  },
  {
    id: 7,
    title: "Industrial Foundation Project",
    category: "Industrial",
    location: "Industrial Zone North",
    budget: "$1.5M",
    duration: "5 months",
    team: "22 workers",
    image: "/images/construction-site-2.jpeg",
    description:
      "Construction of a large circular foundation for a new industrial facility, involving extensive rebar work and concrete pouring.",
    longDescription:
      "This project focused on laying a robust and precise circular foundation for a new heavy industrial facility. The work involved extensive excavation, intricate rebar cage assembly, and large-scale concrete pouring using specialized equipment to ensure uniformity and strength. Given the critical nature of the foundation for the future industrial machinery, precision and adherence to engineering specifications were paramount. The project was completed ahead of schedule, providing a solid base for the client's expansion.",
    features: [
      "Large circular foundation",
      "Extensive rebar reinforcement",
      "High-volume concrete pouring",
      "Precision engineering for heavy loads",
      "Accelerated completion timeline",
    ],
    challenges: [
      "Achieving precise circular dimensions for the foundation",
      "Managing large-scale concrete pours in a single continuous operation",
      "Ensuring structural integrity for future heavy industrial equipment",
    ],
    solutions: [
      "Advanced laser surveying and formwork techniques",
      "Coordinated concrete delivery and pumping logistics",
      "Rigorous quality control and material testing throughout the pour",
    ],
    status: "Completed",
    year: "2024",
    galleryImages: [
      "/images/construction-site-1.jpeg",
      "/images/construction-site-2.jpeg",
      "/images/construction-site-3.jpeg",
      "/images/construction-site-4.jpeg",
      "/images/project-gallery-10.jpeg", // New image
      "/images/project-gallery-11.jpeg", // New image
      "/images/project-gallery-12.jpeg", // New image
      "/images/project-gallery-13.jpeg", // New image
      "/images/project-gallery-14.jpeg", // New image
    ],
  },
  {
    id: 8,
    title: "Community Temple Construction",
    category: "Community", // Changed category to 'Community' for better representation
    location: "Rural Community Center",
    budget: "$0.7M",
    duration: "8 months",
    team: "15 workers",
    image: "/images/temple-building.jpeg",
    description: "Construction of a beautiful community temple, serving as a spiritual and cultural hub.",
    longDescription:
      "We had the honor of constructing a beautiful community temple, designed to serve as a spiritual and cultural hub for the local rural community. The project incorporated traditional architectural elements with modern construction techniques to ensure durability and longevity. Special attention was paid to intricate carvings and decorative finishes, reflecting the cultural significance of the structure. This temple stands as a testament to community spirit and our ability to deliver projects with deep cultural value.",
    features: [
      "Traditional architectural design",
      "Intricate carvings and decorative finishes",
      "Durable and long-lasting construction",
      "Community gathering spaces",
      "Integration of local craftsmanship",
    ],
    challenges: [
      "Sourcing specialized traditional materials",
      "Working with intricate design details and craftsmanship",
      "Coordinating with community stakeholders and religious leaders",
    ],
    solutions: [
      "Partnerships with local artisans and material suppliers",
      "Detailed mock-ups and iterative design reviews",
      "Regular community meetings and transparent communication",
    ],
    status: "Completed",
    year: "2020",
    galleryImages: [
      "/images/temple-building.jpeg",
      "/images/project-temple.jpeg",
      "/images/project-gallery-7.jpeg",
      "/images/project-gallery-8.jpeg",
    ],
  },
]
